#include <Arduino.h>
#include <WiFi.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>
#include <ElegantOTA.h>
#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEUtils.h>
#include <BLE2902.h>
#include <ElegantOTA.h>

const char* SSID = "WeatherStation";
const char* PASSWORD = "password";

#define BATTERY_VOLTAGE 9
#define WIND_DIRECTION 15
#define WIND_SPEED 17
#define SAMPLE_TIME 10              // [ms]  
#define WIFI_TIMEOUT 90000          // [ms] == 90 sec   
#define LOOP_SLEEP_TIME 2000        // [ms]
#define ANEMOMETER_RADIUS 0.1       // [m]
#define SPEED_SAMPLE_NUMBER 30
#define DIRECTION_SAMPLE_NUMBER 10
#define MAX_BATTERY_VOLTAGE 4.2     // [V]
#define MIN_BATTERY_VOLTAGE 2.5     // [V]

#define ADC_POWER 3.3               // [V]
#define ADC_RESOLUTION 4095         // bit
#define ADC_OFFET 0.074             // [V]

/**
 * @brief The baud rate for serial communication.
 *
 * This constant sets the data transfer rate for the serial port,
 */
const unsigned long SERIAL_BAUD = 115200;

/**
 * @brief The delay in milliseconds after serial communication is initialized.
 *
 * This delay provides a brief pause after setting up the serial port,
 * allowing the serial connection to stabilize before any data transmission begins.
 * It can be useful to ensure that the connected device is ready to receive commands or data.
 */
const unsigned long DELAY_AFTER_SERIAL_INITIALIZED = 50;

/**
 * @brief The name of the BLE server/device.
 *
 * This name is displayed when scanning for BLE devices.
 */
const char *BLE_SERVER_NAME = "Weather station";


/**
 * @brief A GATT characteristic that can publish sensor data.
 */
const char *TELEMETRY_UUID = "38938a29-7798-4dd6-bca2-c8fc70f65bfc";

/**
 * @brief Centralized function for sending debug or telemetry messages to both Telnet clients and the serial monitor.
 * 
 * Checks if a Telnet client is connected. If yes, sends the given string (message) to the Telnet client. 
 * Always echoes the same message to the serial port for local debugging.
 * 
 * @param message   String to print
 */
void publishToTelnet(String message);

/**
 * @brief To read and determine the current wind direction from an analog wind vane sensor and return it as a 
 * human-readable direction (e.g., "N", "SW", "E").
 * 
 * Reads the analog input from the wind direction sensor. Stores recent readings in a circular buffer (WindDirection[]). 
 * Computes the average analog value over the latest samples to smooth fluctuations.  * Maps the averaged analog 
 * voltage to a cardinal direction based on predefined ranges. Sends intermediate and final values to Telnet for 
 * logging/debugging.
 */
String GetWindDirection();

/**
 * @brief To calculate the average wind speed (in meters per second) based on pulse counts from a rotating anemometer.
 * 
 * Disables interrupts temporarily to safely copy and reset the global pulse counter (pulseCount). 
 * Calculates wind speed using: radius, elapsed time. Maintains a circular buffer (WindSpeed[]) of recent measurements 
 * for smoothing. Computes the average wind speed over a set number of samples. Returns this averaged speed as a String for 
 * transmission and display. Logs intermediate results through Telnet.
 */
String GetWindSpeed(void);

/**
 * @brief Interrupt Service Routine (ISR) that counts the pulses generated by the anemometer’s reed switch or hall sensor. 
 * Two pulses correspond to a full rotations of the wind cup.
 * 
 * Triggered on each rising edge interrupt from the wind speed sensor pin. Uses millis() to timestamp each interrupt 
 * and apply a debounce filter (SAMPLE_TIME) to avoid false triggers. Increments pulseCount safely, which is later 
 * used by GetWindSpeed(). 
 * The IRAM_ATTR keyword ensures the function is stored in instruction RAM, allowing execution directly from RAM
 *  instead of flash (faster and safer for interrupts).
 */
void IRAM_ATTR countPulse();